name: email_sending

on:
  issues:
    types: [opened, edited, milestoned]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Send email
        env:
          USER_EMAIL: emailsending127@gmail.com
          USER_PASSWORD: cwhaunpbfufqbeey
          TO_MAIL: lakt127@gmial.com
        run: python email_sending.py
